from tkinter import*
ram=Tk()
ram.title('login') # to change the title name from tk to login
ram.geometry('300x400')
ram.resizable(1,0)
# ram.iconbitmap('abc.ico')
a=Label(ram,text='Hello python')
a.pack(side='top')
ram.mainloop()

from tkinter import*
ram=Tk()
ram.title('registration')
ram.geometry('500x500')
ram.resizable(0,1)
ram.iconbitmap('assignment.ico')
ram.config(bg='green')
a=Label(ram,text='Dinesh',font=80, fg='red')
a.pack(side='top')
b=Label(ram,text='Kunwar',font=80, fg='yellow')
b.pack(side='right')
c=Label(ram,text='c',font=80, fg='blue')
c.pack(side='left')
d=Label(ram,text='d',font=80, fg='blue')
d.pack(side='bottom')
e=Label(ram,text='e',font=80, fg='black')
e.pack(fill=X, expand=True)
f=Label(ram,text='tinkenter',font=80, fg='white')
f.place(x=200, y=400)
ram.mainloop()


from tkinter import*
ram=Tk()
ram.geometry('300x300')
ram.resizable(1,1)
ram.config(bg='green')
a=Label(ram,text='Hello',font=80,fg='red')
a.place(x=0, y=0)
b=Label(ram,text='Hello',font=80,fg='red')
b.place(x=30, y=30)
b=Label(ram,text="Hello",font=80,fg="red")
b.place(x=60,y=60)
ram.mainloop()